travis:
  secure:
    BINSTAR_TOKEN: lj3wuyl3seHj3wourNfRkGlpSmLjsvJVn5GXBLP4/NSqvE6MqPGjrjdbpKvMLoUnX/C+J4ENmKSILePSIp0A0nttR4+QTYeKjN8kxWbk+Pw4/b0WnnNDAyP55XRA6RG7YGOjoRuokR/wFe335hpOrfdxHCNgOSR2lyWKodFv42Yl8uB8GPXTDkoyDyow6oYIb5Znbkhp3IPbeSrOS6EITDiHteAFQccG0gkJ4fK3HQM5Of45uytjHjApofetdAJJukg4DMDI0U4ujvO/Ze0fL8cZMka7yyru+61WL/q8G3COSu8IEWgpMlz7tMwH9XWIeg7NnD3NF5HwMzxn2acGT7ldxDWPCc/lb/lozIVg1UxEttvt73kZCA0FA35nPGr6JOri+W4w/Yp1pef2rTMyhmEwhMonqLrT9+/vFhFbicNRbgeYfauQhDs8mpR6pndyTDz0dMxjVArb1uFLc/MGu4QJZR/z/uD7BK5rLPB3pg7YM2CvSP7FuMmdWYlVa055pYuFHYC+XOnjP8cNrc8FniY+7GuXdVWJOnLBAUVx88pg8uhEpwuJT3uVuF1W292m7ucwrQqNhw/KrNKdx7b1xds36HOazfZbjGcYiPO2nPb/RFnW6s7Uo0lK/bW6TwOCaGgaSJ6pVQbtY5NyCw4f3vVpGxA4fqD2G77+6kQC41Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
