travis:
  secure:
    BINSTAR_TOKEN: MRWjeluo7PA/mtD3hJPn5edBk68E3hjBwD7xbExKzDJo5q+HSD7MF8nAF39CvhD3UD1/KxrNR2EYOKbD/eGKgxvgh5TXCkeT7utMvllH0cO7TJS3ySDQAmM3CykEsVrOFwF/Kszxbc4mSoSIs4F7pu8YcRzw5o+rldsSasbOqzP5G08lEHGgZ0qJASnTesPxITQSQ36szbCurtEngfq/4wzkaBYkhFpdtMDj2iahuJI2/d38xc/CchhlmRTQlW14/6IG3T2W++JTnUkevD+pkqDqgqCot2QJ2yl79j9Khpfd+NwDtMs+gj0LhZJqDPxl64kvyyILi8Kx4G0CAAiXE4yI7pYU8goLWA5X9bZ9DREZyc40zkAurzzdCn5GO39sZtkwjhbpMXvBYRNuGbgvdVHDeOCnfE0Uv6pyxQuerE/ZwWR5NxUjqmZzyChcfFk0lrkL1WCFXhuOoZ+An5CvtHF2931A6GuBT926lQfh2BAI4QzxYfGCxZZ0Jyej36JukYOvmWRb0qJqwMCHDbUJ2URqNg9DD8VW7Qhxxrt78EDLfymRFhbINK3hsAW0zdckFShaOIV5g+fNcAVan0i73aXibwJdTHq+LQnXwIVxX4IfL7NkL8R+7H11Y/q+YMTFJK5/bN4NH7LgFBsa6W8lPGj6a7NEKwL5GaOu3/gTJuY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
